# Generated by Django 3.2.7 on 2021-09-21 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_alter_note_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='tag',
            field=models.CharField(default='', max_length=200),
        ),
    ]
